# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "a-mcf/Win2012R2-WMF5-min"
    config.vm.provision "chef_solo" do |chef|
    chef.add_recipe "chef_dsc_simple"
  end
end
